### ISSUE TITLE
Object to string

### ISSUE THREAD

**Issue by akastrin** [jtreanor/LPmade-Python#1]
Hi,

I just install LPmade-Python library. I created the network object:

```
network = WeightedNetwork.readNetworkNamed("adjacency_list.INPUT")
```

Now the problem arises. Suppose you call `edgeCount` method on network object. Is it possible to convert the number of edges which is of type

```
>>> type(network.edgeCount)
<type 'instancemethod'>
```

to string (or integer in this case)?

Best, Andrej

**Comment by jtreanor** [comment]
Hi Andrej,

Thanks for using my project :)

In the example you have given, there is a simple solution. `edgeCount` is an instance method on the WeightedNetwork class. It must be called on you network object at below (note the parentheses):

```
>>> network = WeightedNetwork.readNetworkNamed("adjacency_list.INPUT")
>>> network.edgeCount()
8
```

However you do raise a greater question which is worth addressing. Although integers, as in this case, are passed without trouble, other C++ types require a little more effort to deal with.
To this end, I provide the facility to pass lists the library in the form of C++ vectors. You can use the IntVector and DoubleVector classes for this:

```
v = IntVector()
v.append(1)
v.append(2)

#v can now be passed to the library and will be seen as a vector<int>
```

The IntVector template and others are defined in LPmade.i

For more details about how SWIG handles C++ type, see the [SWIG website](http://www.swig.org/Doc1.3/Python.html)

I hope this helps. Please feel free to ask me any other questions about this project.

Cheers,
James

**Comment by akastrin** [comment]
Hi James,

thanks for quick reply. It's awesome library/wrapper.

Best, Andrej

**Comment by jtreanor** [comment]
No problem :+1:

**Comment by akastrin** [comment]
Hi James,

I'm still learning, so please be patient :). I can now compute basic statistics for a given network. I have three questions regarding link prediction.

First, when specifying similarity measure, for example:
`cn = CommonNeighborLinkPredictor(training_network, training_network)`
argument `training_network` appears two times in the list. I don't understand why.

Second, in the example you provided you calculated performance measures using the `LinkPredictionEnsemble` class. I wonder if there is a shorter way in case you only have one similarity measure?

Third, is there a way to evaluate all possible links in test network (i.e., compute ROC curve, AUC measure)?

Thanks in advance for your time.

Best, Andrej

**Comment by jtreanor** [comment]
Andrej,

First,
`training_network` appears twice here to allow the use of network mutations in directed networks. For example:

```
undirected_network = training_network.undirected() #You can also use reversed()
cn = CommonNeighborLinkPredictor(undirected_network, training_network)
```

This example computes common neighbors while treating the network as undirected. The original network is still needed by the predictor so that existing edges always score 0.
If your data is undirected you don't need worry about this.

Second,
Not directly, but you can simply provide just one measure to the ensemble (RecommenderResult could be easily modified to support a LinkPredictor in place of a LinkPredictorEnsemble):

```
alg = AlgorithmManager(training_network, 
                       IntVector(AlgorithmManager.COMMON_NEIGHBOURS),
                       IntVector(AlgorithmManager.DIRECTED)

#Create a mean ensemble predictor using common neighbours
ensemble = LinkPredictorEnsemble(training_network,
                                 DoubleVector(1.0), #Weights
                                 IntVector(0), #Don't use neighbourhood limiting
                                 LinkPredictorEnsemble.MEAN,
                                 alg)

#Evaluate Common Neighbors using hold out to give with precision at 10.
recommenderResult = RecommenderResult( test_network,
                                       ensemble )
precision_at_10 = recommenderResult.evaluate(10,0,test_network.vertexCount() )
```

Third,
No, this is not something I included. `RecommenderResult` could be extended to support this. The original LPmade has support for some more measures (see: [here](https://github.com/rlichtenwalter/LPmade/tree/master/metrics))

Happy to help,
James

**Comment by akastrin** [comment]
Thanks!

When I use `DoubleVector(1.0)` in

```
ensemble = LinkPredictorEnsemble(training_network,
                                 DoubleVector(1.0), #Weights
                                 IntVector(0), #Don't use neighbourhood limiting
                                 LinkPredictorEnsemble.MEAN,
                                 alg)
```

it breaks with an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/LPmade.py", line 508, in __init__
    this = _LPmade.new_DoubleVector(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_DoubleVector'.
  Possible C/C++ prototypes are:
    std::vector< double >::vector()
    std::vector< double >::vector(std::vector< double > const &)
    std::vector< double >::vector(std::vector< double >::size_type)
    std::vector< double >::vector(std::vector< double >::size_type,std::vector< double >::value_type const &)
```

**Comment by jtreanor** [comment]
Sorry about that, it should be:

```
ensemble = LinkPredictorEnsemble(training_network,
                                 DoubleVector([1.0]), #Weights
                                 IntVector([0]), #Don't use neighbourhood limiting
                                 LinkPredictorEnsemble.MEAN,
                                 alg)
```

Also: pull requests are welcome :)
